---
- name: 'openjdk {{openjdk_version}} = {{openjdk_state}}'
  apt:
    name: openjdk-{{openjdk_version}}-jre
    state: '{{openjdk_state}}'
  become: true
  tags:
  - ct-openjdk
  - ct-openjdk-pkg
...
