---
- name: 'openjdk-{{openjdk_jdk_or_jre} v{{openjdk_version}} --> {{openjdk_state}}'
  apt:
    name: openjdk-{{openjdk_version|int}}-{{openjdk_jdk_or_jre}}
    state: '{{openjdk_state}}'
  become: true
  tags:
  - ct-openjdk
...
